# Generated by Django 3.0.3 on 2020-08-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todomodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='DateCompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
